// 
// Generated by 卓;
// GenerateDate  5/11/2009 9:49:10 AM;
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Medical.Framework.Base.Impl;
using Medical.Framework.Util;
using Dao;
using Medical.Framework.Base.Entity;
using System.Collections;
using Entity;

namespace Business
{
    public class MstOrderBiz : AbsBizBase
    {
        //根据患者ID查询患者最近一次受付信息
        public MstOrderEntity GetLeastOrder(AppParam appParam)
        {
            string patientID = Convert.ToString(appParam.Get("patientId"));
            MstOrderDao mstOrderDao = CreateDaoInstance(typeof(MstOrderDao)) as MstOrderDao;
            MstOrderEntity mstOrderEntity = mstOrderDao.GetLeastOrder(patientID);
            return mstOrderEntity;
        }

        //根据患者受付ID删除患者受付信息
        public bool DeleteOrder(AppParam appParam)
        {
            bool flag = false;            //是否删除成功
            string receptionid = Convert.ToString(appParam.Get("receptionid"));
            MstOrderDao mstOrderDao = CreateDaoInstance(typeof(MstOrderDao)) as MstOrderDao;
            flag = mstOrderDao.DeleteEntityById(receptionid);
            return flag;
        }

        //更新患者受付信息
    }
}
