// 
// Generated by 卓;
// GenerateDate  5/11/2009 9:49:10 AM;
//
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Medical.Framework.Base.Impl;
using Medical.Framework.Util;
using Dao;
using Medical.Framework.Base.Entity;
using System.Collections;
using Entity;

namespace Business
{
    public class PatientBiz : AbsBizBase
    {
        //根据患者ID查询患者基本信息
        public PatientEntity GetPatientByID(AppParam appParam)
        {
            string patientId = Convert.ToString(appParam.Get("patientId"));
            PatientDao patientDao = CreateDaoInstance(typeof(PatientDao)) as PatientDao;
            PatientEntity patient = patientDao.FindEntityByKey(patientId) as PatientEntity;
            return patient;
        }
    }
}
