// 
// Generated by 卓;
// GenerateDate  5/8/2009 11:22:17 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using System.Collections;
using Medical.Framework.Base.Impl;

namespace Entity
{	
	
	[Serializable]
	public class MstCodeEntityKey
	{
		private String _code;

        private String _codeClass;
	
		[KeyProperty(Column="Code")]
		public String Code
		{
			get
			{
			return this._code;
			}
			set
			{
			this._code = value;
			}
		}

  		[KeyProperty(Column="CodeClass")]
		public String CodeClass
		{
			get
			{
			return this._codeClass;
			}
			set
			{
			this._codeClass = value;
			}
		}

  
		
		public override int GetHashCode()
		{
			return _code.GetHashCode()^_codeClass.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			if (this == obj)
			{
				return true;
			}
			MstCodeEntityKey key = obj as MstCodeEntityKey;
			if (key == null)
			{
				return false;
			}
			if (_code != key._code||_codeClass != key._codeClass)
			{
				return false;
			}
			return true;
		}
	}

	[Serializable]
	[ActiveRecord("MstCode")]
	public class MstCodeEntity : BaseEntity 
	{
		
		#region プライベート
		
		private MstCodeEntityKey _key;

        private Int32 _dispOrder;

        private String _name;

        private System.DateTime? _updateTime;

        		
		#endregion

		#region 属性
		
		[CompositeKey]
		public MstCodeEntityKey Key
		{
			get { return _key; }
			set { _key = value; }
		}

  		[Property(Column="DispOrder")]
		public Int32 DispOrder
		{
			get
			{
			return this._dispOrder;
			}
			set
			{
			this._dispOrder = value;
			}
		}

  		[Property(Column="Name")]
		public String Name
		{
			get
			{
			return this._name;
			}
			set
			{
			this._name = value;
			}
		}

  		[Version(Type="timestamp")]
		public System.DateTime? UpdateTime
		{
			get
			{
			return this._updateTime;
			}
			set
			{
			this._updateTime = value;
			}
		}

  
		#endregion


	}
}
