// 
// Generated by 卓;
// GenerateDate  5/8/2009 11:22:18 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using System.Collections;
using Medical.Framework.Base.Impl;

namespace Entity
{	
	
	[Serializable]
	[ActiveRecord("MstDiagnosisDept")]
	public class MstDiagnosisDeptEntity : BaseEntity 
	{
		
		#region プライベート
		
		private String _diagnosisDeptCD;

        private String _diagnosisDeptName;

        private Int32 _dispOrder;

        private String _remarks;

        private System.DateTime? _updateTime;

        		
		#endregion

		#region 属性
		
		[PrimaryKey(PrimaryKeyType.Assigned, Column="DiagnosisDeptCD")]
		public String DiagnosisDeptCD
		{
			get
			{
			return this._diagnosisDeptCD;
			}
			set
			{
			this._diagnosisDeptCD = value;
			}
		}

  		[Property(Column="DiagnosisDeptName")]
		public String DiagnosisDeptName
		{
			get
			{
			return this._diagnosisDeptName;
			}
			set
			{
			this._diagnosisDeptName = value;
			}
		}

  		[Property(Column="DispOrder")]
		public Int32 DispOrder
		{
			get
			{
			return this._dispOrder;
			}
			set
			{
			this._dispOrder = value;
			}
		}

  		[Property(Column="Remarks")]
		public String Remarks
		{
			get
			{
			return this._remarks;
			}
			set
			{
			this._remarks = value;
			}
		}

  		[Version(Type="timestamp")]
		public System.DateTime? UpdateTime
		{
			get
			{
			return this._updateTime;
			}
			set
			{
			this._updateTime = value;
			}
		}

  
		#endregion


	}
}
