// 
// Generated by 卓;
// GenerateDate  5/8/2009 11:22:17 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using System.Collections;
using Medical.Framework.Base.Impl;

namespace Entity
{	
	
	[Serializable]
	[ActiveRecord("MstDoctor")]
	public class MstDoctorEntity : BaseEntity 
	{
		
		#region プライベート
		
		private String _diagnosisDeptCD;

        private Int32 _dispOrder;

        private String _doctorCD;

        private String _doctorName;

        private String _mailAddress;

        private String _phoneNumber;

        private String _remarks;

        private System.DateTime? _updateTime;

        		
		#endregion

		#region 属性
		
		[Property(Column="DiagnosisDeptCD")]
		public String DiagnosisDeptCD
		{
			get
			{
			return this._diagnosisDeptCD;
			}
			set
			{
			this._diagnosisDeptCD = value;
			}
		}

  		[Property(Column="DispOrder")]
		public Int32 DispOrder
		{
			get
			{
			return this._dispOrder;
			}
			set
			{
			this._dispOrder = value;
			}
		}

  		[PrimaryKey(PrimaryKeyType.Assigned, Column="DoctorCD")]
		public String DoctorCD
		{
			get
			{
			return this._doctorCD;
			}
			set
			{
			this._doctorCD = value;
			}
		}

  		[Property(Column="DoctorName")]
		public String DoctorName
		{
			get
			{
			return this._doctorName;
			}
			set
			{
			this._doctorName = value;
			}
		}

  		[Property(Column="MailAddress")]
		public String MailAddress
		{
			get
			{
			return this._mailAddress;
			}
			set
			{
			this._mailAddress = value;
			}
		}

  		[Property(Column="PhoneNumber")]
		public String PhoneNumber
		{
			get
			{
			return this._phoneNumber;
			}
			set
			{
			this._phoneNumber = value;
			}
		}

  		[Property(Column="Remarks")]
		public String Remarks
		{
			get
			{
			return this._remarks;
			}
			set
			{
			this._remarks = value;
			}
		}

  		[Version(Type="timestamp")]
		public System.DateTime? UpdateTime
		{
			get
			{
			return this._updateTime;
			}
			set
			{
			this._updateTime = value;
			}
		}

  
		#endregion


	}
}
