// 
// Generated by 卓;
// GenerateDate  5/8/2009 11:22:18 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using System.Collections;
using Medical.Framework.Base.Impl;

namespace Entity
{	
	
	[Serializable]
	[ActiveRecord("MstDrugProduct")]
	public class MstDrugProductEntity : BaseEntity 
	{
		
		#region プライベート
		
		private Int32 _dispOrder;

        private String _drugProductAbbrName;

        private String _drugProductCD;

        private String _drugProductName;

        private String _drugProductTypeCD;

        private System.DateTime? _updateTime;

        		
		#endregion

		#region 属性
		
		[Property(Column="DispOrder")]
		public Int32 DispOrder
		{
			get
			{
			return this._dispOrder;
			}
			set
			{
			this._dispOrder = value;
			}
		}

  		[Property(Column="DrugProductAbbrName")]
		public String DrugProductAbbrName
		{
			get
			{
			return this._drugProductAbbrName;
			}
			set
			{
			this._drugProductAbbrName = value;
			}
		}

  		[PrimaryKey(PrimaryKeyType.Assigned, Column="DrugProductCD")]
		public String DrugProductCD
		{
			get
			{
			return this._drugProductCD;
			}
			set
			{
			this._drugProductCD = value;
			}
		}

  		[Property(Column="DrugProductName")]
		public String DrugProductName
		{
			get
			{
			return this._drugProductName;
			}
			set
			{
			this._drugProductName = value;
			}
		}

  		[Property(Column="DrugProductTypeCD")]
		public String DrugProductTypeCD
		{
			get
			{
			return this._drugProductTypeCD;
			}
			set
			{
			this._drugProductTypeCD = value;
			}
		}

  		[Version(Type="timestamp")]
		public System.DateTime? UpdateTime
		{
			get
			{
			return this._updateTime;
			}
			set
			{
			this._updateTime = value;
			}
		}

  
		#endregion


	}
}
