// 
// Generated by 卓;
// GenerateDate  5/8/2009 11:22:18 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using System.Collections;
using Medical.Framework.Base.Impl;

namespace Entity
{	
	
	[Serializable]
	[ActiveRecord("MstOrder")]
	public class MstOrderEntity : BaseEntity 
	{
		
		#region プライベート
		
		private String _bloodTypeABO;

        private String _bloodTypeRH;

        private String _comment;

        private String _diagnosisDeptCD;

        private String _diseaseCD;

        private String _doctorCD;

        private String _height;

        private String _patientID;

        private String _receptionDate;

        private String _receptionID;

        private String _receptionNo;

        private System.DateTime? _updateTime;

        private String _wardCD;

        private String _weight;

        		
		#endregion

		#region 属性
		
		[Property(Column="BloodTypeABO")]
		public String BloodTypeABO
		{
			get
			{
			return this._bloodTypeABO;
			}
			set
			{
			this._bloodTypeABO = value;
			}
		}

  		[Property(Column="BloodTypeRH")]
		public String BloodTypeRH
		{
			get
			{
			return this._bloodTypeRH;
			}
			set
			{
			this._bloodTypeRH = value;
			}
		}

  		[Property(Column="Comment")]
		public String Comment
		{
			get
			{
			return this._comment;
			}
			set
			{
			this._comment = value;
			}
		}

  		[Property(Column="DiagnosisDeptCD")]
		public String DiagnosisDeptCD
		{
			get
			{
			return this._diagnosisDeptCD;
			}
			set
			{
			this._diagnosisDeptCD = value;
			}
		}

  		[Property(Column="DiseaseCD")]
		public String DiseaseCD
		{
			get
			{
			return this._diseaseCD;
			}
			set
			{
			this._diseaseCD = value;
			}
		}

  		[Property(Column="DoctorCD")]
		public String DoctorCD
		{
			get
			{
			return this._doctorCD;
			}
			set
			{
			this._doctorCD = value;
			}
		}

  		[Property(Column="Height")]
		public String Height
		{
			get
			{
			return this._height;
			}
			set
			{
			this._height = value;
			}
		}

  		[Property(Column="PatientID")]
		public String PatientID
		{
			get
			{
			return this._patientID;
			}
			set
			{
			this._patientID = value;
			}
		}

  		[Property(Column="ReceptionDate")]
		public String ReceptionDate
		{
			get
			{
			return this._receptionDate;
			}
			set
			{
			this._receptionDate = value;
			}
		}

  		[PrimaryKey(PrimaryKeyType.Assigned, Column="ReceptionID")]
		public String ReceptionID
		{
			get
			{
			return this._receptionID;
			}
			set
			{
			this._receptionID = value;
			}
		}

  		[Property(Column="ReceptionNo")]
		public String ReceptionNo
		{
			get
			{
			return this._receptionNo;
			}
			set
			{
			this._receptionNo = value;
			}
		}

  		[Version(Type="timestamp")]
		public System.DateTime? UpdateTime
		{
			get
			{
			return this._updateTime;
			}
			set
			{
			this._updateTime = value;
			}
		}

  		[Property(Column="WardCD")]
		public String WardCD
		{
			get
			{
			return this._wardCD;
			}
			set
			{
			this._wardCD = value;
			}
		}

  		[Property(Column="Weight")]
		public String Weight
		{
			get
			{
			return this._weight;
			}
			set
			{
			this._weight = value;
			}
		}

  
		#endregion


	}
}
