// 
// Generated by 卓;
// GenerateDate  5/8/2009 11:22:18 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using System.Collections;
using Medical.Framework.Base.Impl;

namespace Entity
{	
	
	[Serializable]
	public class MstWardEntityKey
	{
		private String _diagnosisDeptCD;

        private String _wardCD;

        
		
		[KeyProperty(Column="DiagnosisDeptCD")]
		public String DiagnosisDeptCD
		{
			get
			{
			return this._diagnosisDeptCD;
			}
			set
			{
			this._diagnosisDeptCD = value;
			}
		}

  		[KeyProperty(Column="WardCD")]
		public String WardCD
		{
			get
			{
			return this._wardCD;
			}
			set
			{
			this._wardCD = value;
			}
		}

  
		
		public override int GetHashCode()
		{
			return _diagnosisDeptCD.GetHashCode()^_wardCD.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			if (this == obj)
			{
				return true;
			}
			MstWardEntityKey key = obj as MstWardEntityKey;
			if (key == null)
			{
				return false;
			}
			if (_diagnosisDeptCD != key._diagnosisDeptCD||_wardCD != key._wardCD)
			{
				return false;
			}
			return true;
		}
	}

	[Serializable]
	[ActiveRecord("MstWard")]
	public class MstWardEntity : BaseEntity 
	{
		
		#region プライベート
		
		private MstWardEntityKey _key;

        private Int32 _dispOrder;

        private String _remarks;

        private System.DateTime? _updateTime;

        private String _wardName;

        		
		#endregion

		#region 属性
		
		[CompositeKey]
		public MstWardEntityKey Key
		{
			get { return _key; }
			set { _key = value; }
		}

  		[Property(Column="DispOrder")]
		public Int32 DispOrder
		{
			get
			{
			return this._dispOrder;
			}
			set
			{
			this._dispOrder = value;
			}
		}

  		[Property(Column="Remarks")]
		public String Remarks
		{
			get
			{
			return this._remarks;
			}
			set
			{
			this._remarks = value;
			}
		}

  		[Version(Type="timestamp")]
		public System.DateTime? UpdateTime
		{
			get
			{
			return this._updateTime;
			}
			set
			{
			this._updateTime = value;
			}
		}

  		[Property(Column="WardName")]
		public String WardName
		{
			get
			{
			return this._wardName;
			}
			set
			{
			this._wardName = value;
			}
		}

  
		#endregion


	}
}
