// 
// Generated by 卓;
// GenerateDate  5/8/2009 11:22:18 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using System.Collections;
using Medical.Framework.Base.Impl;

namespace Entity
{	
	
	[Serializable]
	[ActiveRecord("Patient")]
	public class PatientEntity : BaseEntity 
	{
		
		#region プライベート
		
		private String _address;

        private String _birthPlace;

        private String _bloodTypeABO;

        private String _bloodTypeRH;

        private String _diagnosisDeptCD;

        private String _height;

        private String _patientBirthDate;

        private String _patientID;

        private String _patientName;

        private String _phoneNumber;

        private String _postCode;

        private String _sex;

        private System.DateTime? _updateTime;

        private String _wardCD;

        private String _weight;

        		
		#endregion

		#region 属性
		
		[Property(Column="Address")]
		public String Address
		{
			get
			{
			return this._address;
			}
			set
			{
			this._address = value;
			}
		}

  		[Property(Column="BirthPlace")]
		public String BirthPlace
		{
			get
			{
			return this._birthPlace;
			}
			set
			{
			this._birthPlace = value;
			}
		}

  		[Property(Column="BloodTypeABO")]
		public String BloodTypeABO
		{
			get
			{
			return this._bloodTypeABO;
			}
			set
			{
			this._bloodTypeABO = value;
			}
		}

  		[Property(Column="BloodTypeRH")]
		public String BloodTypeRH
		{
			get
			{
			return this._bloodTypeRH;
			}
			set
			{
			this._bloodTypeRH = value;
			}
		}

  		[Property(Column="DiagnosisDeptCD")]
		public String DiagnosisDeptCD
		{
			get
			{
			return this._diagnosisDeptCD;
			}
			set
			{
			this._diagnosisDeptCD = value;
			}
		}

  		[Property(Column="Height")]
		public String Height
		{
			get
			{
			return this._height;
			}
			set
			{
			this._height = value;
			}
		}

  		[Property(Column="PatientBirthDate")]
		public String PatientBirthDate
		{
			get
			{
			return this._patientBirthDate;
			}
			set
			{
			this._patientBirthDate = value;
			}
		}

  		[PrimaryKey(PrimaryKeyType.Assigned, Column="PatientID")]
		public String PatientID
		{
			get
			{
			return this._patientID;
			}
			set
			{
			this._patientID = value;
			}
		}

  		[Property(Column="PatientName")]
		public String PatientName
		{
			get
			{
			return this._patientName;
			}
			set
			{
			this._patientName = value;
			}
		}

  		[Property(Column="PhoneNumber")]
		public String PhoneNumber
		{
			get
			{
			return this._phoneNumber;
			}
			set
			{
			this._phoneNumber = value;
			}
		}

  		[Property(Column="PostCode")]
		public String PostCode
		{
			get
			{
			return this._postCode;
			}
			set
			{
			this._postCode = value;
			}
		}

  		[Property(Column="Sex")]
		public String Sex
		{
			get
			{
			return this._sex;
			}
			set
			{
			this._sex = value;
			}
		}

  		[Version(Type="timestamp")]
		public System.DateTime? UpdateTime
		{
			get
			{
			return this._updateTime;
			}
			set
			{
			this._updateTime = value;
			}
		}

  		[Property(Column="WardCD")]
		public String WardCD
		{
			get
			{
			return this._wardCD;
			}
			set
			{
			this._wardCD = value;
			}
		}

  		[Property(Column="Weight")]
		public String Weight
		{
			get
			{
			return this._weight;
			}
			set
			{
			this._weight = value;
			}
		}

  
		#endregion


	}
}
