// 
// Generated by 卓;
// GenerateDate  5/8/2009 11:22:18 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using System.Collections;
using Medical.Framework.Base.Impl;

namespace Entity
{	
	
	[Serializable]
	public class SpecimenAttributeEntityKey
	{
		private String _receptionID;

        private String _specimenID;

        
		
		[KeyProperty(Column="ReceptionID")]
		public String ReceptionID
		{
			get
			{
			return this._receptionID;
			}
			set
			{
			this._receptionID = value;
			}
		}

  		[KeyProperty(Column="SpecimenID")]
		public String SpecimenID
		{
			get
			{
			return this._specimenID;
			}
			set
			{
			this._specimenID = value;
			}
		}

  
		
		public override int GetHashCode()
		{
			return _receptionID.GetHashCode()^_specimenID.GetHashCode();
		}

		public override bool Equals(object obj)
		{
			if (this == obj)
			{
				return true;
			}
			SpecimenAttributeEntityKey key = obj as SpecimenAttributeEntityKey;
			if (key == null)
			{
				return false;
			}
			if (_receptionID != key._receptionID||_specimenID != key._specimenID)
			{
				return false;
			}
			return true;
		}
	}

	[Serializable]
	[ActiveRecord("SpecimenAttribute")]
	public class SpecimenAttributeEntity : BaseEntity 
	{
		
		#region プライベート
		
		private SpecimenAttributeEntityKey _key;

        private String _attributeID;

        private String _attributeName;

        private System.DateTime? _attributeValueD;

        private Int32 _attributeValueI;

        private System.Decimal _attributeValueR;

        private String _attributeValueS;

        private String _type;

        private System.DateTime? _updateTime;

        		
		#endregion

		#region 属性
		
		[CompositeKey]
		public SpecimenAttributeEntityKey Key
		{
			get { return _key; }
			set { _key = value; }
		}

  		[Property(Column="AttributeID")]
		public String AttributeID
		{
			get
			{
			return this._attributeID;
			}
			set
			{
			this._attributeID = value;
			}
		}

  		[Property(Column="AttributeName")]
		public String AttributeName
		{
			get
			{
			return this._attributeName;
			}
			set
			{
			this._attributeName = value;
			}
		}

  		[Property(Column="AttributeValueD")]
		public System.DateTime? AttributeValueD
		{
			get
			{
			return this._attributeValueD;
			}
			set
			{
			this._attributeValueD = value;
			}
		}

  		[Property(Column="AttributeValueI")]
		public Int32 AttributeValueI
		{
			get
			{
			return this._attributeValueI;
			}
			set
			{
			this._attributeValueI = value;
			}
		}

  		[Property(Column="AttributeValueR")]
		public System.Decimal AttributeValueR
		{
			get
			{
			return this._attributeValueR;
			}
			set
			{
			this._attributeValueR = value;
			}
		}

  		[Property(Column="AttributeValueS")]
		public String AttributeValueS
		{
			get
			{
			return this._attributeValueS;
			}
			set
			{
			this._attributeValueS = value;
			}
		}

  		[Property(Column="Type")]
		public String Type
		{
			get
			{
			return this._type;
			}
			set
			{
			this._type = value;
			}
		}

  		[Version(Type="timestamp")]
		public System.DateTime? UpdateTime
		{
			get
			{
			return this._updateTime;
			}
			set
			{
			this._updateTime = value;
			}
		}

  
		#endregion


	}
}
