// 
// Generated by 卓;
// GenerateDate  5/11/2009 9:49:10 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using Entity;
using Medical.Framework.Base.Impl;
using Medical.Framework.AOP.Attrs;
using Medical.Framework.Base.Entity;

namespace Dao
{
    [Bean(typeof(MstOrderEntity))]
    public abstract class MstOrderDao : BaseDao
    {
        [Sql("select * from mstorder where patientID=:patientID and  receptionDate = (select max(receptionDate) from mstorder where patientID=:patientID)")]
        public abstract MstOrderEntity GetLeastOrder(string patientID);

        [Sql("delete from mstorder where receptionid =:receptionid")]
        public abstract bool DeleteEntityById(string receptionid);

    }
}
