// 
// Generated by 卓;
// GenerateDate  5/11/2009 9:49:10 AM;
//
using System;
using System.Collections.Generic;
using Castle.ActiveRecord;
using Entity;
using Medical.Framework.Base.Impl;
using Medical.Framework.AOP.Attrs;
using Medical.Framework.Base.Entity;

namespace Dao
{
    [Bean(typeof(PatientEntity))]
    public abstract class PatientDao : BaseDao
    {
        [Sql("select * from Patient where PatientID = :PatientID")]
        public abstract PatientEntity GetPatientInfo(string PatientID);
    }
}
